### ISSUE TITLE
Skip Song Feature

### ISSUE THREAD

**Issue by lukemarshburn** [BluDood/GlanceThing#1]
**Is your feature request related to a problem? Please describe.**
I currently do not see a way to skip songs currently. One of the main things I use the CarThing is to easily skip a song without alt tabbing. Add the ability to skip songs on Spotify.

**Describe the solution you'd like**
I think it would really enhance the UX if you could double tap the Spotify album cover to skip the  current song. It would not change the layout if the album cover was turned into a button. 

**Describe alternatives you've considered**
~~Add "skip" and "previous" buttons to left and right of play/pause button.~~  This would probably not be the best due to screen size and would interfere with the volume scrolling

**Additional context**
Really exited to see where the project goes next.

**Comment by BluDood** [comment]
Hey! Thank you for the feature request. I'm already thinking of a way to implement it, the way you explained it sounds amazing! I'll probably make it customizable, I also have an idea to make the dial have double- and triple-press actions which can be used for skipping forwards/back.

**Comment by BluDood** [comment]
Added a couple buttons for skipping (and made the other ones clickable), and made the cover image pause/play, skip forwards or skip back with a single, double and triple press respectively. Any feedback on this @lukemarshburn? :)

![firefox_NhOQcYaOM6](https://github.com/user-attachments/assets/63928db7-1bae-408f-82f0-cdec01f69da5)

**Comment by lukemarshburn** [comment]
It think it looks good. I like the animation since it helps give visual feedback.

**Comment by BluDood** [comment]
> It think it looks good. I like the animation since it helps give visual feedback. Did you make the scroll wheel button able to skip also?

I have not made that a feature yet, since currently it is used to adjust volume. I'm planning on making all actions customizable, so I'll definitely add it there :)
