### ISSUE TITLE
Now playing seekbar for music

### ISSUE THREAD

**Issue by TechGeek01** [BluDood/GlanceThing#11]
**Describe the solution you'd like**
The slider at the bottom of the now playing widget thing for volume is nice, but really only needed when adjusting volume. More useful would be a slider that shows the playhead and progress of the song, similar to how the stock firmware handles this, and perhaps only showing the volume slider when changing volume.

**Comment by BluDood** [comment]
Sounds like a good idea, I'll try a couple different designs and see what turns out the best. There isn't a lot of width to work on though, so I guess it wouldn't be too precise

**Comment by TechGeek01** [comment]
Regarding the space issue, perhaps it may also be possible to make the shortcuts and lock widgets narrower, and the media widget a bit wider, if the user doesn't have a lot of shortcuts, and there's room to do so?

**Comment by BluDood** [comment]
I agree that it would be great to at least see the progress of the current track, so I'll at least implement that. I could also only show the volume slider when the sound is being adjusted as you mentioned to save some space :)

**Comment by BluDood** [comment]
Here's how I've currently implemented it:
https://github.com/user-attachments/assets/dd0272d5-12b8-4f17-8452-c123da745e73

Looks good? Any other feedback? @TechGeek01

**Comment by TechGeek01** [comment]
I might suggest making the height of that seekbar be the same height as the volume one, just for consistency, but looks good!

Making the right widgets narrower and the media widget wider would also give more room for more precision there, but I also dunno what you have planned that would be affected by shrinking the other widgets.

Looks sick!

**Comment by BluDood** [comment]
The progress bar can't be used to actually seek, I kind of made the seekbar thinner to indicate that. I'm planning a UI update which will also make the Spotify area larger, maybe I'll implement it then :)
