### ISSUE TITLE
Volume dial controls not working

### ISSUE THREAD

**Issue by TechGeek01** [BluDood/GlanceThing#13]
**Describe the bug**
In v0.0.4 and v0.0.5, the volume dial controls do not work.

**To Reproduce**
1. Play anything
2. Attempt to adjust volume or click the dial to play/pause

**Expected behavior**
Clicking the dial should play/pause, and rotating the dial should adjust volume.

**Desktop (please complete the following information):**
 - OS: Windows 11 (23H2 build 22631.4391)
 - GlanceThing version: v0.0.5 (also v0.0.4)

**Additional context**
I recall this working if I recall correctly in v0.0.3, but this no longer works as of v0.0.4

**Comment by BluDood** [comment]
> Hah, that does indeed do the trick!
> 
> Is there any reason that it wouldn't make sense to have it control media all the time? Perhaps a toggle in the settings to change that behavior?

The initial thought of the app was that you mostly used the dial to control everything, and you used the top buttons to change what the dial did. I'm working on a new interface which will rework how the app is navigated, and that will most likely use the dial solely for playback controls :)

**Comment by BluDood** [comment]
I've tracked the design update [here](https://github.com/users/BluDood/projects/1?pane=issue&itemId=86245370), closing this :)
