### ISSUE TITLE
Blank shortcut

### ISSUE THREAD

**Issue by phist210** [BluDood/GlanceThing#22]
**Describe the bug**
I accidentally created a blank shortcut after attempting to add a shortcut with no image using the companion app.

**To Reproduce**
1. Go to GlanceThing companion app on MacOS
2. Add a shortcut without an image.

**Expected behavior**
A blank icon should be visible on the CarThing that functions but is not visible in and cannot be removed using the companion app.

**Desktop (please complete the following information):**
 - OS: MacOS 15.1
 - GlanceThing version: [v0.0.6-1]

**Comment by phist210** [comment]
ps: shout out Calibre in the README screenshot

**Comment by phist210** [comment]
Update:
Rebooting and restarting GlanceThing fixed the issue. After this cycle, I could see the blank icons in GlanceThing.

**Comment by BluDood** [comment]
Oh, I probably forgot to check if an image had been set. Will be fixed :)
