### ISSUE TITLE
Adds shortcuts not in one of the empty spaces

### ISSUE THREAD

**Issue by InDaZiploc** [BluDood/GlanceThing#27]
When I add a shortcut, it'll add it outside of the 8 empty spaces for some reason. I'm on a Mac Mini, Sequoia 15.1.1

To reproduce:
Open Glancething Mac desktop app
Add a shortcut (any shortcut)

I expected it to add to one of the empty spaces, but it instead goes to spot off of the screen.

 - OS: Sequoia 15.1.1
 - GlanceThing version: v.0.0.6-1

I did install the desktop app using Pacifist, and the device previously had DeskThing installed.

![IMG_4871](https://github.com/user-attachments/assets/24653da7-d848-4d96-a89a-edd7a9463f18)

**Comment by InDaZiploc** [comment]
Ended up solving itself.

**Comment by BluDood** [comment]
Looks like an issue with the fact there isn't any icon attached, will implement a check for that in the future
