### ISSUE TITLE
blank square after adding shortcuts

### ISSUE THREAD

**Issue by Louis-G-0828** [BluDood/GlanceThing#7]
I am seeing a square in the shortcuts that is not connected to anything restarted both app and device and persists 

![image](https://github.com/user-attachments/assets/05a1889d-cc80-4fad-9edc-59bc5f973a3b)

**Comment by BluDood** [comment]
Hey! Does the same square appear in the desktop app? The square indicates that the image failed to load, perhaps a broken/invalid file?

**Comment by Louis-G-0828** [comment]
It was not originally but after restarting my pc it shows thanks for the info
