### ISSUE TITLE
Stuck on the welcome screen

### ISSUE THREAD

**Issue by nprodas** [BluDood/GlanceThing#9]
Completed setup on GlanceThing, got the message "CarThing is Ready"
On the CarThing its stuck on the welcome screen saying to open GlanceThing and follow instructions

**Comment by BluDood** [comment]
Hey! Have you used the correct image as specified in the wiki? Seems like an issue where ADB detects the device is connected and that the app is installed, but the networking part isn't working.

**Comment by BluDood** [comment]
Could you try the new release [v0.0.4](https://github.com/BluDood/GlanceThing/releases/tag/v0.0.4)? Some users have reported it fixed the issue.

**Comment by nprodas** [comment]
Found the issue, windows 11 was blocking the server from starting. Tried it on my desktop and it worked on v0.0.3. Thank you for your hard work!

**Comment by TTTechnoPro** [comment]
@BluDood Unfortunately I'm having these issues on macOS Sequoia 15.3 and Windows 11. Any tips on to get past this screen?
